[versions]
junit = "5.12.2"
assertj = "3.27.7"
jackson = "2.19.0"
slf4j = "2.0.17"
logback = "1.5.18"
jacoco = "0.8.13"
spotless = "7.0.4"
agp = "8.7.3"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.12.2" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
android-application = { id = "com.android.application", version.ref = "agp" }
